### ISSUE TITLE
BUG - Terminal crashed after 491ish exports

### ISSUE THREAD

**Issue by ctparadise** [Helicer/batch-text2speech#22]

**Comment by ctparadise** [comment]
After running it in the background, and leaving it alone while doing other stuff, it's last export is 492 (out of 2,600+ and it crashed after that.

► Created: _TTS-Output/EW-FW/492 - - - -.mp3
► Created: _TTS-Output/FW-EW-FP-EP/492 - - - - - 这只狗狗这么乖，我们把它领养带回家吧？ - -.mp3
► Created: _TTS-Output/EW-FW-EP-FP/492 - - - - - - - 这只狗狗这么乖，我们把它领养带回家吧？.mp3
► Created: _TTS-Output/EP/492 - -.mp3
► Created: _TTS-Output/FP/492 - 这只狗狗这么乖，我们把它领养带回家吧？.mp3
► Created: _TTS-Output/FP+Pause/492 - 这只狗狗这么乖，我们把它领养带回家吧？.mp3
► Created: _TTS-Output/FP+Pause (Slow)/492 - 这只狗狗这么乖，我们把它领养带回家吧？.mp3
► Created: _TTS-Output/FW-EW/493 - - - -.mp3
► Created: _TTS-Output/EW-FW/493 - - - -.mp3
Traceback (most recent call last):
  File "./tts.py", line 516, in <module>
    main()
  File "./tts.py", line 502, in main
    tts_from_csv(input_file)
  File "./tts.py", line 408, in tts_from_csv
    combine_audio_files_to_mp3(audio_files, filename_format, template_2_dir)
  File "./tts.py", line 317, in combine_audio_files_to_mp3
    concat_wav_files(audio_files, output_dir + workspace_dir + filename_format + ".wav")
  File "./tts.py", line 232, in concat_wav_files
    with open(ffmpeg_concat_list_filename, "w") as concat_list_file:
FileNotFoundError: [Errno 2] No such file or directory: '493 - - - - - 楼价这么高，你有钱买/付首期吗？ - -.txt'
Cliffs-MacBook-Pro-2:batch-text2speech cp$

**Comment by ctparadise** [comment]
Here's the csv I ran.
[example_chinese.csv.zip](https://github.com/Helicer/batch-text2speech/files/4533077/example_chinese.csv.zip)

**Comment by Helicer** [comment]
Speculation: The "/" in the text
`-,-,楼价这么高，你有钱买/付首期吗？,-` (line 493) is likely being interpreted as a directory path in the filename.

**Comment by Helicer** [comment]
Created issue #23  to address this

**Comment by Helicer** [comment]
```

--------[ Converting PCM to WAV ]--------
DEBUG:root:Input filename: _TTS-Output/_Workspace/Joanna - - - 100.pcm
DEBUG:root:Output filename: _TTS-Output/_Workspace/Joanna - - - 100.wav
DEBUG:root:FFMPEG PCM to WAV CMD: 
ffmpeg -y -f s16le -ar 16000 -ac 1 -i "_TTS-Output/_Workspace/Joanna - - - 100.pcm" "_TTS-Output/_Workspace/Joanna - - - 100.wav"
DEBUG:root:FFMPEG PCM to WAV standard output: 

DEBUG:root:FFMPEG PCM to WAV error output: 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[s16le @ 0x7fa8e3813a00] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, s16le, from '_TTS-Output/_Workspace/Joanna - - - 100.pcm':
  Duration: 00:00:00.74, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le, 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '_TTS-Output/_Workspace/Joanna - - - 100.wav':
  Metadata:
    ISFT            : Lavf58.29.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc58.54.100 pcm_s16le
size=      23kB time=00:00:00.73 bitrate= 256.8kbits/s speed= 496x    
video:0kB audio:23kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.330508%

DEBUG:root:Text to WAV - Output filename: _TTS-Output/_Workspace/Joanna - - - 100.wav
DEBUG:root:---[ END: Text to WAV: - ]---
DEBUG:root:

-------[ Text to WAV: 楼价这么高，你有钱买/付首期吗？ ]--------
DEBUG:root:Voice ID: Zhiyu
DEBUG:root:Voice Engine: standard
DEBUG:root:Text: 楼价这么高，你有钱买/付首期吗？
DEBUG:root:Speed: 100
DEBUG:root:

-------[ AWS Polly to PCM ]--------
DEBUG:root:Voice ID: Zhiyu
DEBUG:root:SSML: <speak><prosody rate='100%'>楼价这么高，你有钱买/付首期吗？</prosody></speak>
DEBUG:root:Filename: "_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.pcm"
DEBUG:root:Polly CMD: 
aws polly synthesize-speech --output-format pcm --sample-rate 16000 --text-type ssml --voice-id Zhiyu --engine standard --text "<speak><prosody rate='100%'>楼价这么高，你有钱买/付首期吗？</prosody></speak>" "_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.pcm"
DEBUG:root:Polly CMD standard output: 

DEBUG:root:Polly CMD error output: 

[Errno 2] No such file or directory: '_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.pcm'

DEBUG:root:

--------[ Converting PCM to WAV ]--------
DEBUG:root:Input filename: _TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.pcm
DEBUG:root:Output filename: _TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.wav
DEBUG:root:FFMPEG PCM to WAV CMD: 
ffmpeg -y -f s16le -ar 16000 -ac 1 -i "_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.pcm" "_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.wav"
DEBUG:root:FFMPEG PCM to WAV standard output: 

DEBUG:root:FFMPEG PCM to WAV error output: 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.pcm: No such file or directory

DEBUG:root:Text to WAV - Output filename: _TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.wav
DEBUG:root:---[ END: Text to WAV: 楼价这么高，你有钱买/付首期吗？ ]---
DEBUG:root:

-------[ Text to WAV: 楼价这么高，你有钱买/付首期吗？ ]--------
DEBUG:root:Voice ID: Zhiyu
DEBUG:root:Voice Engine: standard
DEBUG:root:Text: 楼价这么高，你有钱买/付首期吗？
DEBUG:root:Speed: 80
DEBUG:root:

-------[ AWS Polly to PCM ]--------
DEBUG:root:Voice ID: Zhiyu
DEBUG:root:SSML: <speak><prosody rate='80%'>楼价这么高，你有钱买/付首期吗？</prosody></speak>
DEBUG:root:Filename: "_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.pcm"
DEBUG:root:Polly CMD: 
aws polly synthesize-speech --output-format pcm --sample-rate 16000 --text-type ssml --voice-id Zhiyu --engine standard --text "<speak><prosody rate='80%'>楼价这么高，你有钱买/付首期吗？</prosody></speak>" "_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.pcm"
DEBUG:root:Polly CMD standard output: 

DEBUG:root:Polly CMD error output: 

[Errno 2] No such file or directory: '_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.pcm'

DEBUG:root:

--------[ Converting PCM to WAV ]--------
DEBUG:root:Input filename: _TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.pcm
DEBUG:root:Output filename: _TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.wav
DEBUG:root:FFMPEG PCM to WAV CMD: 
ffmpeg -y -f s16le -ar 16000 -ac 1 -i "_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.pcm" "_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.wav"
DEBUG:root:FFMPEG PCM to WAV standard output: 

DEBUG:root:FFMPEG PCM to WAV error output: 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.pcm: No such file or directory

DEBUG:root:Text to WAV - Output filename: _TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 80.wav
DEBUG:root:---[ END: Text to WAV: 楼价这么高，你有钱买/付首期吗？ ]---
DEBUG:root:

-------[ Text to WAV: - ]--------
DEBUG:root:Voice ID: Joanna
DEBUG:root:Voice Engine: neural
DEBUG:root:Text: -
DEBUG:root:Speed: 100
DEBUG:root:

-------[ AWS Polly to PCM ]--------
DEBUG:root:Voice ID: Joanna
DEBUG:root:SSML: <speak><prosody rate='100%'>-</prosody></speak>
DEBUG:root:Filename: "_TTS-Output/_Workspace/Joanna - - - 100.pcm"
DEBUG:root:Polly CMD: 
aws polly synthesize-speech --output-format pcm --sample-rate 16000 --text-type ssml --voice-id Joanna --engine neural --text "<speak><prosody rate='100%'>-</prosody></speak>" "_TTS-Output/_Workspace/Joanna - - - 100.pcm"
DEBUG:root:Polly CMD standard output: 
{
    "ContentType": "audio/pcm",
    "RequestCharacters": "1"
}

DEBUG:root:Polly CMD error output: 

DEBUG:root:

--------[ Converting PCM to WAV ]--------
DEBUG:root:Input filename: _TTS-Output/_Workspace/Joanna - - - 100.pcm
DEBUG:root:Output filename: _TTS-Output/_Workspace/Joanna - - - 100.wav
DEBUG:root:FFMPEG PCM to WAV CMD: 
ffmpeg -y -f s16le -ar 16000 -ac 1 -i "_TTS-Output/_Workspace/Joanna - - - 100.pcm" "_TTS-Output/_Workspace/Joanna - - - 100.wav"
DEBUG:root:FFMPEG PCM to WAV standard output: 

DEBUG:root:FFMPEG PCM to WAV error output: 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[s16le @ 0x7fc66d814000] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, s16le, from '_TTS-Output/_Workspace/Joanna - - - 100.pcm':
  Duration: 00:00:00.74, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le, 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to '_TTS-Output/_Workspace/Joanna - - - 100.wav':
  Metadata:
    ISFT            : Lavf58.29.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc58.54.100 pcm_s16le
size=      23kB time=00:00:00.73 bitrate= 256.8kbits/s speed= 782x    
video:0kB audio:23kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.330508%

DEBUG:root:Text to WAV - Output filename: _TTS-Output/_Workspace/Joanna - - - 100.wav
DEBUG:root:---[ END: Text to WAV: - ]---
DEBUG:root:

-------[ Combine Audio files to MP3 ]--------
DEBUG:root:Audio files: ['_TTS-Output/_Workspace/silence_1.0s.wav', '_TTS-Output/_Workspace/Zhiyu - - - 100.wav', '_TTS-Output/_Workspace/silence_1.5s.wav', '_TTS-Output/_Workspace/Joanna - - - 100.wav', '_TTS-Output/_Workspace/silence_1.0s.wav']
DEBUG:root:Filename format: 493 - - - -
DEBUG:root:Template directory: FW-EW/
DEBUG:root:

--------[ Concat WAV files  ]--------
DEBUG:root:Output filename: _TTS-Output/_Workspace/493 - - - -.wav
DEBUG:root:FFMPEG Concat list filename:493 - - - -.txt
DEBUG:root:FFMPEG Concat CMD: 
ffmpeg -y -f concat -safe 0 -i "493 - - - -.txt" -c copy "_TTS-Output/_Workspace/493 - - - -.wav"
DEBUG:root:FFMPEG Concat standard output: 

DEBUG:root:FFMPEG Concat error output: 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, concat, from '493 - - - -.txt':
  Duration: N/A, start: 0.000000, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Output #0, wav, to '_TTS-Output/_Workspace/493 - - - -.wav':
  Metadata:
    ISFT            : Lavf58.29.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     133kB time=00:00:04.16 bitrate= 262.5kbits/s speed= 455x    
video:0kB audio:133kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.057091%

DEBUG:root:

--------[ Convert WAV to MP3  ]--------
DEBUG:root:Input filename: _TTS-Output/_Workspace/493 - - - -.wav
DEBUG:root:Output filename: _TTS-Output/FW-EW/493 - - - -.mp3
DEBUG:root:FFMPEG Convert WAV to MP3 CMD: 
ffmpeg -i "_TTS-Output/_Workspace/493 - - - -.wav" "_TTS-Output/FW-EW/493 - - - -.mp3"
DEBUG:root:FFMPEG Convert WAV to MP3 standard output: 

DEBUG:root:FFMPEG Convert WAV to MP3 error output: 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from '_TTS-Output/_Workspace/493 - - - -.wav':
  Metadata:
    encoder         : Lavf58.29.100
  Duration: 00:00:04.27, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to '_TTS-Output/FW-EW/493 - - - -.mp3':
  Metadata:
    TSSE            : Lavf58.29.100
    Stream #0:0: Audio: mp3 (libmp3lame), 16000 Hz, mono, s16p
    Metadata:
      encoder         : Lavc58.54.100 libmp3lame
size=      13kB time=00:00:04.28 bitrate=  24.8kbits/s speed= 531x    
video:0kB audio:13kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.721763%

DEBUG:root:Created MP3 from audio files: _TTS-Output/FW-EW/493 - - - -.mp3
► Created: _TTS-Output/FW-EW/493 - - - -.mp3
DEBUG:root:---[ END: Combine mp3 from audio files ]---
DEBUG:root:

-------[ Combine Audio files to MP3 ]--------
DEBUG:root:Audio files: ['_TTS-Output/_Workspace/silence_1.0s.wav', '_TTS-Output/_Workspace/Joanna - - - 100.wav', '_TTS-Output/_Workspace/silence_1.5s.wav', '_TTS-Output/_Workspace/Zhiyu - - - 100.wav', '_TTS-Output/_Workspace/silence_1.0s.wav']
DEBUG:root:Filename format: 493 - - - -
DEBUG:root:Template directory: EW-FW/
DEBUG:root:

--------[ Concat WAV files  ]--------
DEBUG:root:Output filename: _TTS-Output/_Workspace/493 - - - -.wav
DEBUG:root:FFMPEG Concat list filename:493 - - - -.txt
DEBUG:root:FFMPEG Concat CMD: 
ffmpeg -y -f concat -safe 0 -i "493 - - - -.txt" -c copy "_TTS-Output/_Workspace/493 - - - -.wav"
DEBUG:root:FFMPEG Concat standard output: 

DEBUG:root:FFMPEG Concat error output: 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, concat, from '493 - - - -.txt':
  Duration: N/A, start: 0.000000, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Output #0, wav, to '_TTS-Output/_Workspace/493 - - - -.wav':
  Metadata:
    ISFT            : Lavf58.29.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     133kB time=00:00:04.16 bitrate= 262.5kbits/s speed= 461x    
video:0kB audio:133kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.057091%

DEBUG:root:

--------[ Convert WAV to MP3  ]--------
DEBUG:root:Input filename: _TTS-Output/_Workspace/493 - - - -.wav
DEBUG:root:Output filename: _TTS-Output/EW-FW/493 - - - -.mp3
DEBUG:root:FFMPEG Convert WAV to MP3 CMD: 
ffmpeg -i "_TTS-Output/_Workspace/493 - - - -.wav" "_TTS-Output/EW-FW/493 - - - -.mp3"
DEBUG:root:FFMPEG Convert WAV to MP3 standard output: 

DEBUG:root:FFMPEG Convert WAV to MP3 error output: 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from '_TTS-Output/_Workspace/493 - - - -.wav':
  Metadata:
    encoder         : Lavf58.29.100
  Duration: 00:00:04.27, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to '_TTS-Output/EW-FW/493 - - - -.mp3':
  Metadata:
    TSSE            : Lavf58.29.100
    Stream #0:0: Audio: mp3 (libmp3lame), 16000 Hz, mono, s16p
    Metadata:
      encoder         : Lavc58.54.100 libmp3lame
size=      13kB time=00:00:04.28 bitrate=  24.8kbits/s speed= 526x    
video:0kB audio:13kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.721763%

DEBUG:root:Created MP3 from audio files: _TTS-Output/EW-FW/493 - - - -.mp3
► Created: _TTS-Output/EW-FW/493 - - - -.mp3
DEBUG:root:---[ END: Combine mp3 from audio files ]---
DEBUG:root:

-------[ Combine Audio files to MP3 ]--------
DEBUG:root:Audio files: ['_TTS-Output/_Workspace/silence_1.0s.wav', '_TTS-Output/_Workspace/Zhiyu - - - 100.wav', '_TTS-Output/_Workspace/silence_1.5s.wav', '_TTS-Output/_Workspace/Joanna - - - 100.wav', '_TTS-Output/_Workspace/silence_1.5s.wav', '_TTS-Output/_Workspace/Zhiyu - 楼价这么高，你有钱买/付首期吗？ - 100.wav', '_TTS-Output/_Workspace/silence_4s.wav', '_TTS-Output/_Workspace/Joanna - - - 100.wav', '_TTS-Output/_Workspace/silence_1.0s.wav']
DEBUG:root:Filename format: 493 - - - - - 楼价这么高，你有钱买/付首期吗？ - -
DEBUG:root:Template directory: FW-EW-FP-EP/
DEBUG:root:

--------[ Concat WAV files  ]--------
DEBUG:root:Output filename: _TTS-Output/_Workspace/493 - - - - - 楼价这么高，你有钱买/付首期吗？ - -.wav
DEBUG:root:FFMPEG Concat list filename:493 - - - - - 楼价这么高，你有钱买/付首期吗？ - -.txt
Traceback (most recent call last):
  File "./tts.py", line 516, in <module>
    main()
  File "./tts.py", line 502, in main
    tts_from_csv(input_file)
  File "./tts.py", line 408, in tts_from_csv
    combine_audio_files_to_mp3(audio_files, filename_format, template_2_dir)
  File "./tts.py", line 317, in combine_audio_files_to_mp3
    concat_wav_files(audio_files, output_dir + workspace_dir + filename_format + ".wav")
  File "./tts.py", line 232, in concat_wav_files
    with open(ffmpeg_concat_list_filename, "w") as concat_list_file:
FileNotFoundError: [Errno 2] No such file or directory: '493 - - - - - 楼价这么高，你有钱买/付首期吗？ - -.txt'
jro@RGV-MacBookPro19 text-to-speech_aws-polly % 

```
